version: "3.9"

services:
  node-app:
    build: .
    ports:
      - "8000:8000"
  mongo:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lisab
      - MONGO_INITDB_ROOT_PASSWORD=SecretLisab
    volumes:
      - mongo-db:/data/db

  redis:
    image: redis

volumes:
mongo-db:
