version: "3.9"

services:
  node-app:
    build:
      context: .
      args:
        NODE_ENV: development
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - MONGO_USER=lisab
      - MONGO_PASSWORD=SecretLisab
    command: npm run dev
  mongo:
    environment:
      - MONGO_INITDB_ROOT_USERNAME=lisab
      - MONGO_INITDB_ROOT_PASSWORD=SecretLisab
